### ISSUE TITLE
turtlebot üzerine yerleştirlen kinect 360 ile rgb ve depth görüntü 

### ISSUE THREAD

**Issue by xxchenchen** [NevzatBOL/RACLAB#1]
turtlebot üzerine yerleştirlen kinect 360 ile rgb ve depth görüntü nasıl alınır vedepolanır . Tşkler

**Comment by NevzatBOL** [comment]
Mesajınızı yeni gördüm. Çözüm buldunuz mu bilmiyorum.

Kinect için gerekli paketleri çalıştırdığında rostopic ile rgb ve depth görünleri dinleyebilirsin. Kinect kamerayı kullanmak için bazı paketlerin yüklenmesi gerekir. Turtlebot Tutorials içerisinde anlatıyorum. Turtlebot kullanım detaylarına [buradan](https://github.com/NevzatBOL/RACLAB/blob/master/ROS/Turtlebot%20Tutorials.md) bakabilirsin:
